name: Deploy on Push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run build-and-run.sh on remote server
      env:
        SSH_KEY: ${{ secrets.Growth_Frontend_Github_Secret }}
      run: |
        echo "${SSH_KEY}" > ssh_key
        chmod 600 ssh_key
        ssh -o StrictHostKeyChecking=no -i ssh_key root@wangyousong.com 'bash -s' < build-and-run.sh
